package model;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

/**
 * This class represents a playlist with the
 * detailed information of the playlist and operations
 * on the playlist
 */
public class PlayList implements Serializable {
    private static final long serialVersionUID = 1L;

    private String listName;
    private List<Song> songs;
    private boolean isAutoGenerated;

    /**
     * Constructor to create a playlist
     * @param listName input list name
     */
    public PlayList(String listName) {
        this.listName = listName;
        this.songs = new ArrayList<>();
        this.isAutoGenerated = false;
    }

    /**
     * Constructor with auto-generated flag
     * @param listName Playlist name
     * @param isAutoGenerated Whether this is an auto-generated playlist
     */
    public PlayList(String listName, boolean isAutoGenerated) {
        this(listName);
        this.isAutoGenerated = isAutoGenerated;
    }

    /**
     * Get the play list name
     * @return name of the playlist
     */
    public String getListName() {
        return listName;
    }

    /**
     * Get the song list of the play list
     * @return song list
     */
    public List<Song> getSongs() {
        return songs;
    }

    /**
     * Check if this playlist is auto-generated
     * @return true if auto-generated, false otherwise
     */
    public boolean isAutoGenerated() {
        return isAutoGenerated;
    }

    /**
     * Check if the play list contains specified song
     * @param songName input song name
     * @param artist input artist
     * @return true if exists, else false
     */
    public boolean containsSong(String songName, String artist) {
        for (int i = 0; i < songs.size(); i++) {
            Song song = songs.get(i);
            if (song.getTitle().equals(songName) && song.getArtist().equals(artist)) {
                return true;
            }
        }
        return false;
    }

    /**
     * Add song to the play list
     * @param song input song object
     * @return true if add successfully, else false
     */
    public boolean addSong(Song song) {
        for (int i = 0; i < this.songs.size(); i++) {
            if (songs.get(i).equals(song)) {
                return false;
            }
        }
        this.songs.add(song);
        return true;
    }

    /**
     * Remove the song from the play list
     * @param songName input song name
     * @param artist input artist
     * @return true if remove successfully, else return false
     */
    public boolean removeSong(String songName, String artist) {
        int idx = -1;
        for (int i = 0; i < this.songs.size(); i++) {
            Song song = this.songs.get(i);
            if (song.getTitle().equals(songName) && song.getArtist().equals(artist)) {
                idx = i;
                break;
            }
        }
        if (idx != -1) {
            this.songs.remove(idx);
            return true;
        }
        return false;
    }
}